# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image as the base
FROM node:20-slim

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the project
RUN npm run build

# Expose the port the server listens on
EXPOSE 3000

# The Docker image will run the compiled JavaScript
# Use the direct path to the compiled file
ENTRYPOINT ["node", "dist/index.js"]
